// ==UserScript==
// @name          Deezer DarkCube
// @namespace     http://userstyles.org
// @description	  It's my "dark" version of deezer.com for users who like inverted colors that are easier on your eyes.
// @author        cubedj
// @copyright	2017, cubedj (https://twitter.com/cubedj)
// @homepage  https://userstyles.org/styles/142184
// @include       http://deezer.com/*
// @include       https://deezer.com/*
// @include       http://*.deezer.com/*
// @include       https://*.deezer.com/*
// @include       http://deezer.com/*
// @include       https://deezer.com/*
// @include       http://*.deezer.com/*
// @include       https://*.deezer.com/*
// @run-at        document-start
// @version       0.20171212023608
// @exclude      *
// ==/UserScript==
// ==OpenUserJS==
// @author cubedj
// @collaborator username
// ==/OpenUserJS==
(function() {var css = "";
if (false || (document.domain == "deezer.com" || document.domain.substring(document.domain.indexOf(".deezer.com") + 1) == "deezer.com"))
	css += [
		"::selection, ::-moz-selection, ::-webkit-selection {",
		"	color: #000 !important;",
		"	background-color: #0096ff !important;",
		"}",
		"a:active, a:visited {",
		"	color: #0096ff;",
		"}",
		"a:link {",
		"	color: #0096ff !important;",
		"}",
		"a:hover {",
		"	color: #FF6400 !important;",
		"}",
		"input {",
		"	color: #CCC;",
		"	font-weight: bold !important;",
		"}",
		"#livebar_menu a {",
		"	filter: invert(100%);",
		"	-moz-filter: invert(100%);",
		"	-webkit-filter: invert(100%);",
		"	border-color: #FF6400 !important;",
		"	border-left-color: #FF6400 !important;",
		"}",
		"#livebar_menu {",
		"	border-color: #0096ff !important;",
		"}",
		".channel-section {",
		"	background-color: #0a0a0a !important;",
		"}",
		"div.channel-section {",
		"	background-color: #191919 !important;",
		"}",
		".page-sidebar .player-controls > .controls.controls-options .volume-handler, .page-sidebar .player-progress .progress-handler {",
		"	background-color: #FF6400 !important;",
		"}",
		".page-sidebar .player-controls > .controls.controls-options .volume-progress-bar, .page-sidebar .player-progress .progress-buffer {",
		"	background-color: #969696 !important;",
		"}",
		".page-sidebar .player-controls > .controls.controls-options .volume-bar, .page-sidebar .player-progress .progress {",
		"	background-color: #0096ff !important;",
		"}",
		".page-sidebar .player-progress .progress-time, .page-sidebar .player-progress .progress-length {",
		"	color: #ffffff;",
		"	opacity: 1;",
		"}",
		".datagrid-table {",
		"	background: #0a0a0a;",
		"}",
		".datagrid-table tbody tr.active td {",
		"	background-color: rgba(255, 100, 0, .7);",
		"}",
		".datagrid-table tbody tr.active td.length {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.active:hover td.length {",
		"	color: #ff6400;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.active:hover td {",
		"	background-color: rgba(150, 150, 150, .5);",
		"}",
		".datagrid-table tbody tr.active a {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.active:hover a {",
		"	color: #ff6400;",
		"	font-weight: bold;",
		"}",
		"",
		"/*.datagrid-table tbody tr:hover td, .datagrid-table tbody tr:hover {",
		"	filter: invert(100%) hue-rotate(180deg);",
		"} */",
		".datagrid-table tbody tr:hover td {",
		"	background-color: rgba(150, 150, 150, .5);",
		"}",
		".datagrid-table tbody tr:hover td a {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr:hover td.artist {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.song.active:hover td.artist {",
		"	color: #FFF;",
		"	font-weight: bold;",
		"}",
		".datagrid-table tbody tr.song.active td.artist {",
		"	color: #000;",
		"	font-weight: bold;",
		"}",
		".datagrid-table td, .datagrid-table th {",
		"	color: #AAA;",
		"}",
		".datagrid-table td.length {",
		"	color: #ff6400;",
		"}",
		".datagrid-table tbody tr.contributors td {",
		"	background-color: #191919;",
		"	color: #DDD;",
		"	font-weight: normal;",
		"}",
		".datagrid-table tbody tr.contributors:hover td {",
		"	background-color: rgba(150, 150, 150, .5);",
		"	color: #DDD;",
		"}",
		".datagrid-table tbody tr.caption:hover td {",
		"	background-color: rgba(150, 150, 150, 0.5);",
		"	color: #fff;",
		"}",
		".datagrid-table tbody tr.caption:hover td .icon-album {",
		"	color: #ff6400;",
		"}",
		".datagrid-table tbody tr.caption td .icon-album:hover {",
		"	color: #0096ff;",
		"}",
		".icon-datagrid {",
		"	color: #EEE;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".icon-datagrid:hover {",
		"	color: #ff6400;",
		"}",
		".loved .icon.active {",
		"	/*color: #ff0064 !important;*/",
		"	color: #ff0000 !important;",
		"}",
		".loved .icon:hover {",
		"	color: #ff0000 !important;",
		"}",
		".datagrid-table tbody tr td a {",
		"	color: #AAA;",
		"}",
		"a.link-gray {",
		"	color: #AAA;",
		"}",
		"input[type=checkbox] {",
		"	filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"}",
		"body:not(.paused):not([direction=\"ltr\"]) {",
		"	background-color: #0a0a0a !important;",
		"	color: #EEE !important;",
		"	font-family: \"Lucida Grande\", Arial, sans-serif;",
		"	font-size: 12px;",
		"	line-height: 1.33333333;",
		"	margin: 0;",
		"	padding: 0;",
		"}",
		".page-main, .catalog-header {",
		"	background-color: #0a0a0a !important;",
		"	color: #EEE;",
		"}",
		".navbar {",
		"	background-color: #0a0a0a;",
		"	color: #0096ff !important;",
		"	border-bottom: 1px solid #646464;",
		"}",
		".catalog-header .infos {",
		"	border-top: 1px solid #646464;",
		"}",
		"#page_profile .user-section {",
		"	border-bottom: 1px solid #646464;",
		"}",
		"#page_feed .info-down .heading-5.heading-bordered {",
		"	border-bottom: 1px solid #646464;",
		"}",
		"#page_feed .title_separ {",
		"	border-bottom: 1px solid #646464;",
		"}",
		"#page_feed .card-release-album .details ul > li + li {",
		"	border-top: 1px solid #646464;",
		"}",
		".heading-bordered {",
		"	border-bottom: 1px solid #646464;",
		"}",
		"#page_account .account-apps .app-cell {",
		"	border-bottom: 1px solid #646464;",
		"}",
		"div.catalog-content {",
		"	background-color: #0a0a0a;",
		"	color: #FFF;",
		"}",
		"#page_naboo_artist .content-left {",
		"	background-color: #0b0b0b;",
		"}",
		".naboo-catalog .catalog-tab-box, .page-naboo-search .search-header, .page-naboo-search .search-suggest {",
		"	background-color: #0a0a0a;",
		"	/*color: #FFF;*/",
		"}",
		".btn {",
		"	border: 1px solid transparent;",
		"	border-radius: 4px;",
		"	color: #FFF;",
		"	background-color: #0096ff;",
		"	cursor: pointer;",
		"	font-size: 12px;",
		"	margin: 0;",
		"	padding: 7px 12px;",
		"	vertical-align: middle;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, border-color, color, opacity;",
		"}",
		".btn:hover {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".btn .label {",
		"	color: #FFF;",
		"}",
		".btn:hover .label {",
		"	color: #000;",
		"}",
		".line/*, .cell-line*/",
		"{",
		"	background-color: #646464 !important;",
		"}",
		"#page_naboo_artist .content-right {",
		"	border-bottom: 1px solid #646464;",
		"	border-top: 1px solid #646464;",
		"}",
		".btn > .action-active .icon-love {",
		"	color: #ff1e1e;",
		"}",
		".btn-group > .btn.btn-default.active {",
		"	background-color: #444444;",
		"	color: #0096FF;",
		"	border-color: #000;",
		"}",
		".btn-group > .btn.btn-default.active .label {",
		"	color: #ff6400;",
		"}",
		".btn-group > .btn.btn-default.active .icon {",
		"	color: #ff6400;",
		"}",
		".btn-group > .btn.btn-default.active:hover .icon {",
		"	color: #000;",
		"}",
		".btn-group > .btn.btn-default.active:hover .label {",
		"	color: #000;",
		"}",
		".btn-group > .btn.btn-default.active:hover {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"	border-color: #ff6400;",
		"}",
		".page-sidebar/*, .page-main, .page-scroll */",
		"{",
		"	background-color: #0f0f0f;",
		"	color: #EEE;",
		"}",
		".page-main, .page-scroll {",
		"	background-color: #0a0a0a;",
		"	color: #EEE;",
		"}",
		".page-sidebar .nav-link {",
		"	background-color: #0f0f0f;",
		"	color: #EEE;",
		"}",
		"/*.page-sidebar .nav-link:hover {",
		"	background-color: #646464;",
		"	color: #000;",
		"}*/",
		".page-sidebar .nav-link:hover {",
		"	background-color: #333;",
		"	color: #ff6400;",
		"}",
		".page-sidebar .nav-link:focus {",
		"	background-color: #1c1c1c;",
		"}",
		".page-sidebar .nav-link[href=\"/en/profile/1286179544/loved\"]:active {",
		"	background-color: #1c1c1c;",
		"	color: #ff6400;",
		"}",
		".page-sidebar .nav-link[href=\"/en/profile/1286179544/loved\"]:active .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".page-sidebar .nav-link.active-link {",
		"	background-color: #1c1c1c;",
		"	border-left-color: #0096ff;",
		"	color: #eee;",
		"}",
		".page-sidebar .nav-link:hover .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".page-sidebar .nav-link.active-panel {",
		"	background-color: #1c1c1c;",
		"	color: #ff6400;",
		"}",
		".page-sidebar .nav-link.active-panel .svg-icon {",
		"	fill: #0096ff;",
		"}",
		".page-sidebar .player-controls {",
		"	background-color: #0f0f0f;",
		"}",
		".page-sidebar .player-controls:hover {",
		"	background-color: #141414;",
		"}",
		".page-sidebar .player-controls > .controls > li > .control:hover {",
		"	color: #ff6400;",
		"}",
		".page-sidebar .search-control, .form-control ~ .page-panels, .catalog-tab-comment .post-comment .form-control, .datagrid-toolbar .toolbar-search .form-control, #page_profile .user-search .form-control {",
		"	filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"}",
		".page-sidebar .player-controls > .controls > li > .control.control-play:hover {",
		"	color: #ff6400;",
		"}",
		".heading-2 {",
		"	color: #EEE;",
		"}",
		".heading-1 a, .heading-1 a:hover, .heading-2 a, .heading-2 a:hover, .heading-3 a, .heading-3 a:hover, .heading-4 a, .heading-4 a:hover, .heading-5 a, .heading-5 a:hover {",
		"	color: #EEE;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a {",
		"	color: #0096ff;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #0096ff .5px;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a:hover {",
		"	color: #ff6400;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a:visited {",
		"	color: #0096ff;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #0096ff .5px;",
		"}",
		".page-panels .panel-container.opened .panel-wrapper .heading-4 a:visited:hover {",
		"	color: #ff6400;",
		"	text-shadow: 0 0 2px #fff;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"}",
		".page-panels .panel-wrapper/*:not(::after):not(.dropdown-menu), *:not(.search-control) */",
		"{",
		"	/*background-color: #0a0a0a;*/",
		"	filter: invert(96%) hue-rotate(180deg);",
		"	-webkit-filter: invert(96%) hue-rotate(180deg);",
		"	-moz-filter: invert(96%) hue-rotate(180deg);",
		"}",
		"",
		"/*.page-panels .panel-body {",
		"	background-color: #101010;",
		"}",
		".nano-card-item {",
		"	background-color: #181818;",
		"}",
		".nano-card-item:hover {",
		"	background-color: #444;",
		"}",
		".page-panels .panel-header-link:hover {",
		"	background-color: #ff6400;",
		"}",
		".page-panels .panel-header {",
		"	background-color: #101010;",
		"	border-bottom: 1px solid #0096ff;",
		"}",
		".page-panels .panel-header:hover {",
		"	border-bottom: 1px solid #FFF;",
		"}",
		".page-panels .panel-headings:hover .heading-2 {",
		"	color: #FFF;",
		"}",
		".nano-card-link {",
		"	background-color: #161616;",
		"}",
		".nano-card-link:hover {",
		"	background-color: #444;",
		"}*/",
		".page-panels .panel-heading-sub {",
		"	color: #000;",
		"	margin: 24px 0 8px;",
		"}",
		"#page_profile .user-section .user-section-suggestion {",
		"	background-color: #0f0f0f;",
		"}",
		".thumbnail .picture:after {",
		"	background-color: #EEE;",
		"	bottom: 0;",
		"	content: \"\";",
		"	left: 0;",
		"	opacity: 0;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"	box-shadow: none;",
		"}",
		".thumbnail .picture.overlay-hidden {",
		"	background-color: #010101;",
		"}",
		".thumbnail:hover .picture.overlay-hidden {",
		"	background-color: #0096ff;",
		"}",
		".thumbnail {",
		"	box-shadow: none;",
		"}",
		"",
		"/*.thumbnail: .action::hover {",
		"	-webkit-filter: invert(100%);",
		"}*/",
		".btn-app .icon, .btn-default .icon, .btn-group > .btn-label .icon, .btn-slide .icon, .btn-telco .icon {",
		"	color: #000;",
		"}",
		".btn-app:hover .icon, .btn-default:hover .icon, .btn-group > .btn-label:hover .icon, .btn-slide:hover .icon, .btn-telco:hover .icon {",
		"	color: #FFF;",
		"}",
		".btn-group > .btn-label {",
		"	background-color: #444444;",
		"	border: 1px solid #0096ff;",
		"	color: #FFF;",
		"}",
		".btn-group > .btn-label:hover {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".datagrid-table thead th {",
		"	background-color: #2d2d2d;",
		"}",
		"#page_profile .user-listen {",
		"	background-color: #1a1a1a;",
		"	border-radius: 4px;",
		"	height: 40px;",
		"	box-shadow: 0 0 2px 1px rgba(0,150,255,.8);",
		"	border: 5px double rgba(0,0,0,.7);",
		"}",
		".heading-1-sub, .heading-2-sub, .heading-3-sub, .heading-4-sub, .heading-5-sub {",
		"	color: #EEE;",
		"}",
		".heading-4 {",
		"	color: #0096ff;",
		"}",
		".heading-4:hover {",
		"	color: #ff6400;",
		"}",
		".heading-1, .heading-2, .heading-3, .heading-5 {",
		"	color: #EEE;",
		"}",
		".create-assistant-container:hover {",
		"	background-color: #646464;",
		"}",
		".catalog-tab-comment .comment-message {",
		"	background-color: #222;",
		"}",
		".catalog-tab-comment .message-body {",
		"	color: #EEE;",
		"}",
		".navbar-nav > li.active > a {",
		"	color: #FFF;",
		"}",
		".dropdown .dropdown-menu ~ .page-panels, .popover/* > li > a:hover */",
		"{",
		"	/*background-color: #F8F8F9;*/",
		"	/*color: #32323D;*/",
		"	filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"}",
		".page-contextmenu .menu-item:hover {",
		"	background-color: #ff6400;",
		"	color: #FFF;",
		"	-webkit-text-stroke: transparent 0px;",
		"}",
		".page-contextmenu .menu-item:hover .label {",
		"	color: #FFF;",
		"	-webkit-text-stroke: transparent 0px;",
		"}",
		".page-contextmenu .menu-item:hover .icon {",
		"	color: #000;",
		"	-webkit-text-stroke: transparent 0px;",
		"}",
		".page-contextmenu .menu-item.link {",
		"	background-color: transparent;",
		"	/* border-radius: 5px; */",
		"	padding: 0 6px;",
		"}",
		".page-sidebar .nav-link.active-link, .page-sidebar .nav-link.active-panel {",
		"	background-color: #222;",
		"	/*color: #FFF;*/",
		"}",
		"textarea.form-control {",
		"	color: #000;",
		"}",
		"/*.page-panels .panel-header {",
		"	color: #111;",
		"    background-color: rgb(238, 238, 238);",
		"}*/",
		".panel-qlist .panel-headings .heading-2, .page-panels .panel-headings .heading-2 {",
		"	color: #0096ff;",
		"}",
		".panel-qlist .panel-headings .heading-3-sub {",
		"	color: #111;",
		"}",
		".panel-header span {",
		"	color: #0096ff;",
		"}",
		"#page_panels > div > div.panel-wrapper.panel-wrapper-queuelist > div:nth-child(4) > div > div.panel-body.nano.has-scrollbar > div.nano-content > div > div > ul div {",
		"	color: #111 !important;",
		"}",
		".page-naboo-search .suggest-column .nano-card-item {",
		"	background-color: #2d2d2d;",
		"}",
		".page-naboo-search .suggest-column .nano-card-item:hover {",
		"	background-color: #646464;",
		"}",
		".page-naboo-search .suggest-column .nano-card-item:hover a {",
		"	color: #ff6400 !important;",
		"}",
		".modal-dialog, #modal-sharebox {",
		"	background-color: #191919 !important;",
		"}",
		".modal-body, .modal-footer {",
		"	background-color: #191919 !important;",
		"	color: #EEE !important;",
		"}",
		".modal-header {",
		"	color: #0096ff !important;",
		"	background-color: #191919 !important;",
		"	border-bottom-color: #000 !important;",
		"}",
		"#modal_sharebox .share-nav {",
		"	background-color: #0f0f0f !important;",
		"	padding-left: 20px;",
		"}",
		"#modal_sharebox .share-followers {",
		"	background-color: #191919;",
		"	padding-bottom: 0;",
		"}",
		"#modal_sharebox .share-nav-tabs.selected {",
		"	background-color: #0096FF;",
		"	color: #FFF;",
		"}",
		"#modal_sharebox .share-nav-tabs:hover {",
		"	background-color: #ff6400;",
		"	color: #000 !important;",
		"	font-weight: bold;",
		"}",
		"#modal_sharebox .share-nav-tabs {",
		"	border-radius: 5px 5px 0 0;",
		"	color: #EEE;",
		"	float: left;",
		"	line-height: 40px;",
		"	padding: 0 20px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		"#modal_sharebox .share-message {",
		"	color: #EEE;",
		"	background-color: #222;",
		"	border-color: #000;",
		"}",
		".form-control-static {",
		"	background-color: #222;",
		"	color: #0096ff;",
		"	border-color: #0096ff;",
		"}",
		"#modal_sharebox .modal-footer .btn-label {",
		"	color: #FFF;",
		"	cursor: default;",
		"	font-size: 11px;",
		"	font-weight: bold;",
		"	font-weight: 400;",
		"	padding-left: 0;",
		"	padding-right: 0;",
		"}",
		".btn-share:after {",
		"	filter: invert(100%);",
		"	-moz-filter: invert(100%);",
		"	-webkit-filter: invert(100%);",
		"}",
		"#page_feed .card {",
		"	background-color: #121212;",
		"	box-shadow: 0 1px 2px rgba(25, 25, 25, .15);",
		"	margin-top: 20px;",
		"	position: relative;",
		"	transition-duration: .15s;",
		"	transition-property: box-shadow;",
		"}",
		"#page_feed .footer {",
		"	display: block;",
		"	background-color: #222;",
		"	box-sizing: border-box;",
		"	height: 36px;",
		"	padding: 10px 20px;",
		"}",
		"#page_feed .footer > .btn-link + .btn {",
		"	border-left: 1px solid #000;",
		"	margin-left: 10px;",
		"	padding-left: 10px;",
		"}",
		"#page_feed .divider .divider-line {",
		"	background-color: #ff6400;",
		"	height: 1px;",
		"	margin-top: 13px;",
		"	position: absolute;",
		"	width: 100%;",
		"	z-index: 1;",
		"}",
		"#page_feed .divider .divider-text {",
		"	color: #FFF;",
		"	background-color: #ff6400;",
		"	font-size: 11px;",
		"	padding: 0 10px;",
		"	display: inline-block;",
		"	position: relative;",
		"	z-index: 2;",
		"}",
		"",
		"/*#page_feed .card-trending .progress_bar {",
		"	filter: invert(100%) hue-rotate(180deg);",
		"}*/",
		"#page_feed .card-trending .progress-bar-inner {",
		"	background-color: #0096ff;",
		"	height: 40px;",
		"	left: 0;",
		"	position: absolute;",
		"	top: 0;",
		"	width: 0;",
		"	z-index: 20;",
		"}",
		"#page_feed .card-trending .load-bar-inner {",
		"	background-color: #000;",
		"	height: 40px;",
		"	opacity: .5;",
		"	position: absolute;",
		"	top: 0;",
		"	left: 0;",
		"	width: 0;",
		"	z-index: 10;",
		"}",
		"#page_feed .card-trending .waveform {",
		"	background-size: 100% 40px;",
		"	height: 40px;",
		"	left: 0;",
		"	position: absolute;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 30;",
		"	filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"}",
		"#page_feed .card-trending .waveform-design {",
		"	height: 40px;",
		"	left: 0;",
		"	position: absolute;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 40;",
		"	filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"}",
		".popover-header > .cell.cell-thumbnail * img, .page-panels .panel-wrapper .nano-card-picture * img, .notifications-item-media-picture * img:not([src*=\"http://e-cdn-images.deezer.com/images/playlist/d41d8cd98f00b204e9800998ecf8427e/56x56-000000-80-0-0.jpg\"]), .notifications-item-picture * img:not([src*=\"http://e-cdn-images.deezer.com/images/user/d41d8cd98f00b204e9800998ecf8427e/32x32-000000-80-0-0.jpg\"])",
		", #panel-lyrics {",
		"	filter: invert(100%) hue-rotate(180deg);",
		"	-moz-filter: invert(100%) hue-rotate(180deg);",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"}",
		".panel-lyrics.has-lyrics .nano-content {",
		"	-webkit-mask-image: linear-gradient(to bottom,rgba(10,10,10,0) 0,#0a0a0a 20%,#0a0a0a 80%,rgba(10,10,10,0) 100%);",
		"	mask-image: linear-gradient(to bottom,rgba(10,10,10,0) 0,#0a0a0a 20%,#0a0a0a 80%,rgba(10,10,10,0) 100%);",
		"}",
		".page-sidebar .player-cover.has-contextmenu .player-progress .progress-length, .page-sidebar .player-cover.has-contextmenu .player-progress .progress-time, .page-sidebar .player-cover:hover .player-progress .progress-length, .page-sidebar .player-cover:hover .player-progress .progress-time {",
		"	background-color: transparent !important;",
		"	color: #ff6400;",
		"	font-weight: bold;",
		"}",
		".alert-info {",
		"	background-color: #aa0000;",
		"	border-color: #000;",
		"	color: #FFF;",
		"}",
		".popover .heading-4-sub, .page-panels .panel-wrapper .heading-4-sub {",
		"	color: #000;",
		"}",
		"",
		"/*img[src*=\"http://e-cdn-images.deezer.com/images/playlist/d41d8cd98f00b204e9800998ecf8427e/56x56-000000-80-0-0.jpg\"] {",
		"	-webkit-filter: invert(100%) hue-rotate(180deg);",
		"}*/",
		".panel-lyrics .panel-close .icon {",
		"	color: #FFF;",
		"}",
		".panel-lyrics {",
		"	background-color: #000;",
		"	background-position: center center;",
		"	background-repeat: no-repeat;",
		"	background-size: cover;",
		"}",
		".panel-lyrics .lyrics-line {",
		"	color: #FFF;",
		"}",
		"",
		"/*.panel-lyrics .panel-header+.panel-body {",
		"	color: #111;",
		"}*/",
		".panel-lyrics .lyrics-line-active {",
		"	/*background-color: rgba(25, 25, 25, .9);*/",
		"	color: #0096ff;",
		"	-webkit-text-stroke: #0096ff .7px;",
		"	border-radius: 30px;",
		"	box-shadow: 0 0 2px 2px #000;",
		"	background: rgba(25,25,25,0.9);",
		"	background: radial-gradient(circle farthest-corner at center center, rgba(25,25,25,0.9) 15%, rgba(0,0,0,0.5) 100%);",
		"	background: -webkit-radial-gradient(circle farthest-corner at center center, rgba(25,25,25,0.9) 15%, rgba(0,0,0,0.5) 100%);",
		"	background: -moz-radial-gradient(circle farthest-corner at center center, rgba(25,25,25,0.9) 15%, rgba(0,0,0,0.5) 100%);",
		"}",
		".panel-lyrics .lyrics-infos .lyrics-line-active:hover {",
		"	background-color: #191919;",
		"	color: #ff6400 !important;",
		"}",
		".panel-lyrics.has-synchro .lyrics-content .lyrics-line-active:focus, .panel-lyrics.has-synchro .lyrics-content .lyrics-line-active:hover {",
		"	background-color: #191919;",
		"	color: #ff6400 !important;",
		"}",
		".panel-lyrics.has-synchro .lyrics-content .lyrics-line, .panel-lyrics.has-synchro .lyrics-content .lyrics-line:hover {",
		"	border-radius: 30px;",
		"}",
		".panel-lyrics.has-synchro .lyrics-content .lyrics-line:hover {",
		"	-webkit-text-stroke: #ff6400 .7px;",
		"}",
		"",
		"/*.panel-lyrics.has-lyrics .nano-content {",
		"	-webkit-mask-image: linear-gradient(rgba(25,25,25,1.0), transparent);",
		"	mask-image: linear-gradient(rgba(25,25,25,1.0), transparent);",
		"}*/",
		"",
		"/*.panel-lyrics .panel-body {",
		"	background-color: rgba(25,25,25,0.5);",
		"}*/",
		".panel-lyrics .panel-lyrics-overlay {",
		"	background-color: #191919;",
		"	bottom: 0;",
		"	content: \"\";",
		"	left: 0;",
		"	opacity: .60;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"}",
		".page-contextmenu .menu-item.link:hover {",
		"	background-color: #ff6400;",
		"}",
		".thumbnail .action-item-btn.action-active .icon-love {",
		"	/*color: #ff0064;*/",
		"	color: #ff0000;",
		"}",
		"#page_account .account-wrapper {",
		"	background: #0a0a0a;",
		"}",
		"#page_account .form-control {",
		"	background-color: #000;",
		"	border: 1px solid #333;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, border, color;",
		"	color: #fff;",
		"	font-weight: bold;",
		"}",
		"#page_account .account-delete {",
		"	background: #111;",
		"	border-top: 1px solid #646464;",
		"	color: #ff0000;",
		"}",
		"#page_account .account-delete .link-remove {",
		"	color: #ff0000;",
		"}",
		".alert-success {",
		"	background-color: #222;",
		"	border-color: #468847;",
		"	color: #468847;",
		"}",
		"#page_account .account-social .social-table {",
		"	border: 1px solid #333;",
		"	border-collapse: collapse;",
		"	width: 100%;",
		"}",
		"#page_account .account-social .social-cell {",
		"	background-color: #111;",
		"	border: 1px solid #333;",
		"	padding: 15px;",
		"	vertical-align: middle;",
		"	width: 20%;",
		"}",
		"#page_account .account-social .social-options-item {",
		"	background-color: #222;",
		"}",
		"#page_account .account-social .social-options-item:nth-child(2n) {",
		"	background-color: #181818;",
		"}",
		"#page_account .account-social .social-platform-unlink {",
		"	color: #fff;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		"#page_account .account-social .social-platform-unlink::before {",
		"	border-color: transparent transparent #ff6400;",
		"	border-style: solid;",
		"}",
		".channel-horizontalgrid-control {",
		"	border: 1px solid #fff;",
		"	color: #fff;",
		"	background-color: #0096ff;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color, opacity;",
		"}",
		".channel-horizontalgrid-control:hover:not(.disabled) {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".thumbnail-viewmore {",
		"	background-color: #111;",
		"	border: solid 1px #444;",
		"	border-radius: 4px;",
		"	box-shadow: 0 1px 2px 0 rgba(25, 25, 34, .24);",
		"	color: #323232;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".catalog-content .dropdown .dropdown-menu, .user-section .dropdown .dropdown-menu {",
		"	background: #000 !important;",
		"	border: 1px solid #2e2e2e;",
		"	box-shadow: 0 1px 5px rgba(245, 245, 245, .2);",
		"}",
		".catalog-content .dropdown .dropdown-menu > li > a, .catalog-content .dropdown .dropdown-menu > li > button, .user-section .dropdown .dropdown-menu > li > a, .user-section .dropdown .dropdown-menu > li > button {",
		"	background-color: #000;",
		"	box-sizing: border-box;",
		"	color: #0096ff;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color;",
		"}",
		" :not(.datagrid-table) ~ .icon-chevron-down {",
		"	color: #000 !important;",
		"}",
		".btn:hover :not(.datagrid-table) ~ .icon-chevron-down {",
		"	color: #FFF !important;",
		"}",
		".btn-app:hover, .btn-default:hover, .btn-group > .btn-label:hover, .btn-slide:hover, .btn-telco:hover, .btn-upload:hover .btn, .selectbox.opened .btn-group > .dropdown-toggle.btn-label, .selectbox.opened .dropdown-toggle.btn-app, .selectbox.opened .dropdown-toggle.btn-default, .selectbox.opened .dropdown-toggle.btn-slide, .selectbox.opened .dropdown-toggle.btn-telco {",
		"	background-color: #ff6400;",
		"}",
		".catalog-content .dropdown .dropdown-menu > li > a:hover, .catalog-content .dropdown .dropdown-menu > li > button:hover, .user-sectiont .dropdown .dropdown-menu > li > a:hover, .user-section .dropdown .dropdown-menu > li > button:hover {",
		"	background-color: #ff6400;",
		"	color: #000 !important;",
		"	/* 	font-weight: bold; */",
		"}",
		".page-contextmenu .menu-item/*:not(:hover)*/ {",
		"	/* font-weight: bold; */",
		"	-webkit-text-stroke: .6px;",
		"	color: #525252;",
		"}",
		".naboo-catalog .has-alternate-bg {",
		"	background-color: #0a0a0a;",
		"}",
		".page-loader {",
		"	-webkit-backface-visibility: hidden;",
		"	backface-visibility: hidden;",
		"	background-color: #0a0a0a;",
		"	height: 4px;",
		"	left: 0;",
		"	overflow: hidden;",
		"	position: fixed;",
		"	right: 0;",
		"	top: 0;",
		"	-webkit-transform: translateY(-4px);",
		"	-ms-transform: translateY(-4px);",
		"	transform: translateY(-4px);",
		"	z-index: 1000;",
		"	transition-duration: .15s;",
		"	transition-property: -webkit-transform;",
		"	transition-property: transform;",
		"	transition-property: transform,-webkit-transform;",
		"}",
		".datagrid {",
		"	background-color: #0a0a0a;",
		"	color: #ccc;",
		"	display: table;",
		"	font-family: \"Open Sans\", Arial, sans-serif;",
		"	font-size: 14px;",
		"	font-weight: 400;",
		"	table-layout: fixed;",
		"	width: 100%;",
		"}",
		".datagrid-row {",
		"	-webkit-align-items: center;",
		"	-ms-flex-align: center;",
		"	align-items: center;",
		"	border-radius: 4px;",
		"	box-sizing: border-box;",
		"	display: -webkit-flex;",
		"	display: -ms-flexbox;",
		"	display: flex;",
		"	-webkit-flex-wrap: nowrap;",
		"	-ms-flex-wrap: nowrap;",
		"	flex-wrap: nowrap;",
		"	height: 52px;",
		"	padding: 0 16px;",
		"	position: relative;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".datagrid-header .is-sortable .icon,.datagrid-header .is-sortable .svg-icon {",
		"	color: #0096ff;",
		"	line-height: 52px;",
		"	margin-left: 5px;",
		"	opacity: 0;",
		"	position: relative;",
		"	top: 2px;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".datagrid-header .datagrid-row::before, .datagrid-row::before {",
		"	background-color: #333;",
		"	height: 1px;",
		"	left: 6px;",
		"	position: absolute;",
		"	right: 6px;",
		"}",
		".no-flexbox .datagrid-cell {",
		"	display: table-cell;",
		"	line-height: 36px;",
		"	vertical-align: middle",
		"}",
		".datagrid-label-main {",
		"	color: #eee;",
		"}",
		".datagrid-label {",
		"	color: #ccc;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".datagrid-row.song.active {",
		"	background-color: rgba(255, 100, 0, .7);",
		"	color: #eee;",
		"}",
		".datagrid-row.active .datagrid-label {",
		"	color: #fff !important;",
		"}",
		".datagrid-row:hover {",
		"	/*-webkit-filter: invert(100%) hue-rotate(180deg) !important;*/",
		"	background-color: #333;",
		"}",
		".datagrid-header .datagrid-row:hover {",
		"	background-color: #333;",
		"	cursor: default;",
		"}",
		".datagrid-label:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: 0.4px;",
		"	cursor: pointer;",
		"}",
		".datagrid-header .datagrid-label {",
		"	color: #fff;",
		"}",
		".datagrid-action {",
		"	border-radius: 50%;",
		"	color: #eee;",
		"	cursor: pointer;",
		"	display: block;",
		"	font-size: 14px;",
		"	height: 28px;",
		"	line-height: 28px;",
		"	text-align: center;",
		"	width: 28px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color;",
		"}",
		".datagrid-badge-unseen {",
		"	background-color: #0096ff;",
		"	border-radius: 50%;",
		"	height: 8px;",
		"	position: absolute;",
		"	width: 8px;",
		"}",
		"icon-stack-hover .icon {",
		"	color: #ff6400;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".cell-play:hover {",
		"	filter: invert(100%) hue-rotate(180deg) !important;",
		"	-moz-filter: invert(100%) hue-rotate(180deg) !important;",
		"	-webkit-filter: invert(100%) hue-rotate(180deg) !important;",
		"}",
		".cell-play:hover .play-active {",
		"	filter: invert(100%) hue-rotate(0deg) !important;",
		"	-moz-filter: invert(100%) hue-rotate(0deg) !important;",
		"	-webkit-filter: invert(100%) hue-rotate(0deg) !important;",
		"}",
		".datagrid-header .datagrid-label:hover/* .cell-play:hover*/ {",
		"	color: #ff6400 !important;",
		"}",
		".icon.active {",
		"	color: #0096ff !important;",
		"}",
		".icon-love.active {",
		"	color: #ff0000 !important;",
		"}",
		".datagrid-row.song.active .icon-love.active {",
		"	color: #000 !important;",
		"}",
		".datagrid-row.song.active .datagrid-action:hover .icon-love.active {",
		"	color: #ff0000 !important;",
		"}",
		".datagrid-row .datagrid-action:hover .icon-love.active {",
		"	color: #fff !important;",
		"}",
		".banner-header {",
		"	background-color: #0a0a0a;",
		"	padding: 0;",
		"	position: relative;",
		"}",
		".navbar-nav > li > a, .navbar-nav > li > button {",
		"	background-color: transparent;",
		"	border-bottom: 3px solid transparent;",
		"	box-sizing: border-box;",
		"	color: #999;",
		"	display: block;",
		"	font-family: \"Open Sans\", Arial, sans-serif;",
		"	font-weight: 700;",
		"	height: 50px;",
		"	letter-spacing: .5px;",
		"	padding: 0 15px;",
		"	transition-duration: .15s;",
		"	transition-property: border-color, color;",
		"}",
		".naboo-catalog .has-white-bg {",
		"	background-color: #0a0a0a;",
		"}",
		".carousel-control {",
		"	background-color: #0096ff;",
		"	border: 1px solid #444;",
		"	color: #fff;",
		"	cursor: pointer;",
		"	padding: 7px;",
		"	text-align: center;",
		"	transition-duration: .15s;",
		"	transition-property: background-color, color, opacity;",
		"}",
		".carousel-control:hover:not(.disabled) {",
		"	background-color: #ff6400;",
		"	color: #000;",
		"}",
		".slide .slide-background {",
		"	background-color: #111;",
		"	border-radius: 4px;",
		"	height: 100%;",
		"	position: relative;",
		"	width: 100%;",
		"}",
		".slide {",
		"	border-radius: 4px;",
		"	box-shadow: 0 1px 2px rgba(25, 25, 34, .25);",
		"	color: #ddd;",
		"	display: inline-block;",
		"	font-family: \"Open Sans\", Arial, sans-serif;",
		"	max-height: 100%;",
		"	max-width: 100%;",
		"	opacity: 1;",
		"	overflow: hidden;",
		"	position: relative;",
		"	vertical-align: top;",
		"	transition-duration: .15s;",
		"	transition-property: opacity, box-shadow;",
		"}",
		".slide .slide-text .subtitle, .slide .slide-text .subtitle .link {",
		"	color: #999;",
		"}",
		".large-card-inner-infos .heading-label {",
		"	color: #999;",
		"}",
		".thumbnail-caption .caption-released {",
		"	color: #999;",
		"}",
		".slide .slide-btn {",
		"	border: 1px solid #333;",
		"	color: #eee;",
		"	font-size: .7em;",
		"	font-weight: 700;",
		"	margin-top: 1em;",
		"	opacity: 1;",
		"	padding: .4em .9em;",
		"	transition-duration: .15s;",
		"	transition-property: opacity, background-color, color;",
		"}",
		".slide .slide-btn:hover {",
		"	background-color: #ff6400;",
		"	border-color: transparent;",
		"	color: #000;",
		"}",
		".sticker-default {",
		"	background-color: #ff6400;",
		"}",
		"#page_feed .card-release-album .visual {",
		"	border-left: 1px solid #646464;",
		"	float: right;",
		"	height: 352px;",
		"	width: 477px;",
		"}",
		"#page_feed .card-algo-playlist .visual {",
		"	border-right: 1px solid #646464;",
		"	float: left;",
		"	height: 250px;",
		"	width: 250px;",
		"}",
		"#page_feed .card-trending .visual {",
		"	border-right: 1px solid #646464;",
		"	float: left;",
		"	height: 250px;",
		"	width: 250px;",
		"}",
		".btn-tag {",
		"	color: #000;",
		"	-webkit-text-stroke: #000 0.6px;",
		"}",
		".btn-tag:hover {",
		"	color: #fff !important;",
		"	-webkit-text-stroke: #fff 0.0px;",
		"}",
		".page-sidebar .player-track-title .player-track-link {",
		"	color: #fff !important;",
		"	text-shadow: 0 0 3px #0096ff;",
		"}",
		".page-sidebar .player-track-title .player-track-link:hover {",
		"	color: #ff6400 !important;",
		"	-webkit-text-stroke: #ff6400 0.6px;",
		"	text-shadow: 0 0 3px #000;",
		"}",
		".page-sidebar .player-track-artist .player-track-link {",
		"	color: #0096ff !important;",
		"	-webkit-text-stroke: #0096ff 0.6px;",
		"	text-shadow: 0 0 3px #000;",
		"}",
		".page-sidebar .player-track-artist .player-track-link:hover {",
		"	color: #ff6400 !important;",
		"	-webkit-text-stroke: #ff6400 0.6px;",
		"	text-shadow: 0 0 3px #000;",
		"}",
		".page-naboo-search .datagrid-container {",
		"	background-color: #0a0a0a;",
		"}",
		".tooltip {",
		"	background-color: rgba(0,0,0,1.0) !important;",
		"	color: #fff;",
		"	/*border-radius: 5px;*/",
		"}",
		".datagrid-action:hover {",
		"	background-color: #ff6400;",
		"	color: #000 !important;",
		"}",
		".datagrid-row.song.active .datagrid-action:not([aria-label*=\"Add to favourite tracks\"]):hover {",
		"	color: #0096ff !important;",
		"}",
		".datagrid-row.song.active .datagrid-action:hover {",
		"	background-color: #000;",
		"}",
		".datagrid-row.song.active .datagrid-action[aria-label*=\"Add to favourite tracks\"]:hover {",
		"	color: #fff !important;",
		"}",
		".icon-stack-hover:after {",
		"	color: #0096ff;",
		"}",
		".datagrid-row.song.active .icon-stack-hover .icon {",
		"	color: #fff;",
		"}",
		".datagrid-row.song.active .icon-stack-hover:after {",
		"	color: #000;",
		"}",
		".datagrid-row.song.active .datagrid-label:hover {",
		"	color: #000 !important;",
		"	-webkit-text-stroke: #000 0.6px;",
		"}",
		".nano-card-picture {",
		"	border-right: 1px solid #646464;",
		"}",
		".popover-header .heading-4 a, .popover-header .heading-4-sub a {",
		"	color: #0096ff;",
		"	-webkit-text-stroke: #0096ff 0.4px;",
		"}",
		".popover-header .heading-4 a:hover, .popover-header .heading-4-sub a:hover {",
		"	-webkit-text-stroke: 0.4px;",
		"}",
		".color-primary {",
		"	color: #0096ff !important;",
		"}",
		".btn-view-more:after, .icon-chevron-right:before, .link-animated:after {",
		"	content: none;",
		"}",
		".page-panels .panel-overlay {",
		"	background-color: #0a0a0a;",
		"	bottom: 0;",
		"	left: 0;",
		"	opacity: 0;",
		"	position: fixed;",
		"	right: 0;",
		"	top: 0;",
		"	z-index: 200;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".page-panels .panel-container.opened .panel-overlay {",
		"	opacity: .6;",
		"}",
		".page-sidebar .search-control {",
		"	background-color: #e1e1e1;",
		"	border: 0;",
		"	border-radius: 3px;",
		"	box-sizing: border-box;",
		"	color: #424242;",
		"	display: block;",
		"	font-family: \"Lucida Grande\",Arial,sans-serif;",
		"	font-size: 12px;",
		"	height: 32px;",
		"	line-height: 1.33333333;",
		"	padding: 8px 40px 8px 12px;",
		"	width: 100%;",
		"	transition-duration: .15s;",
		"	transition-property: background-color,color;",
		"}",
		".page-sidebar .player-controls>.controls>li>.control.disabled, .page-sidebar .player-controls>.controls>li>.control.disabled:hover, .page-sidebar .player-controls>.controls>li>.control[disabled], .page-sidebar .player-controls>.controls>li>.control[disabled]:hover {",
		"	color: #525252;",
		"	cursor: default;",
		"}",
		".modal-backdrop {",
		"	background-color: #191919;",
		"	height: 100%;",
		"	left: 0;",
		"	opacity: 0;",
		"	position: fixed;",
		"	table-layout: fixed;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 8010;",
		"	transition-duration: .15s;",
		"	transition-property: opacity;",
		"}",
		".modal.opened .modal-backdrop {",
		"	opacity: .8;",
		"}",
		"#notify {",
		"	background-color: #0096ff;",
		"	background-color: rgba(0,150,255,.8);",
		"	display: none;",
		"	left: 0;",
		"	position: fixed;",
		"	text-align: center;",
		"	top: 0;",
		"	width: 100%;",
		"	z-index: 1000;",
		"}",
		".btn-share {",
		"	border: none !important;",
		"}",
		".btn-share::after {",
		"	background-color: #f8f8f8;",
		"	border-bottom-right-radius: 3px;",
		"	border-top-right-radius: 3px;",
		"	color: #323232;",
		"	font-family: \"Deezer Icons\",sans-serif;",
		"	font-size: 16px;",
		"	height: 24px;",
		"	line-height: 24px;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"	width: 28px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".btn-share:hover::after {",
		"	background-color: #0096ff;",
		"	border-bottom-right-radius: 3px;",
		"	border-top-right-radius: 3px;",
		"	color: #fff;",
		"	font-family: \"Deezer Icons\",sans-serif;",
		"	font-size: 16px;",
		"	height: 24px;",
		"	line-height: 24px;",
		"	position: absolute;",
		"	right: 0;",
		"	top: 0;",
		"	width: 28px;",
		"	transition-duration: .15s;",
		"	transition-property: background-color;",
		"}",
		".modal-close {",
		"	color: #777;",
		"	font-size: 16px;",
		"	position: absolute;",
		"	right: 20px;",
		"	top: 20px;",
		"	z-index: 1",
		"}",
		".modal-close:hover {",
		"	color: #ff0000;",
		"	-webkit-text-stroke: #ff0000 .7px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".panel-settings .heading-bordered {",
		"	border-bottom: 1px solid #9b9b9b;",
		"}",
		".checkbox.checked:before {",
		"	background-color: #0096ff;",
		"	border-color: #0096ff;",
		"}",
		".checkbox.checked:hover:before {",
		"	background-color: #ff6400;",
		"	border-color: #ff6400;",
		"}",
		".panel-settings .checkbox .checkbox-tick {",
		"	fill: #000;",
		"}",
		".panel-settings .checkbox:hover .checkbox-tick {",
		"	fill: #fff;",
		"}",
		".panel-settings .nano-card-link.animate-wobble .animate-wobble-target {",
		"	fill: #000;",
		"}",
		".panel-settings .nano-card-link.animate-wobble:hover .animate-wobble-target {",
		"	fill: #ff6400;",
		"}",
		".nano-card-link:focus, .nano-card-link:hover {",
		"	background-color: #e5e5e5;",
		"	outline: 0;",
		"}",
		".panel-settings .rounded-icon-user {",
		"	background-color: #0096ff;",
		"}",
		".panel-settings .rounded-icon-help {",
		"	background-color: #509900;",
		"}",
		".panel-settings .rounded-icon-code {",
		"	background-color: #ee99ff;",
		"}",
		".panel-settings .rounded-icon {",
		"	color: #000;",
		"}",
		"button[data-type=\"log_out\"] .label, .btn-clear .label {",
		"	color: #000 !important;",
		"	-webkit-text-stroke: #000 .6px;",
		"}",
		"button[data-type=\"log_out\"]:hover .label,  .btn-clear:hover .label  {",
		"	color: #fff !important;",
		"	-webkit-text-stroke: #fff 0px;",
		"}",
		":focus {",
		"	outline: none;",
		"}",
		".panel-settings .slider-bar-handler {",
		"	background-color: #ff6400;",
		"	border: 1px solid #dedede;",
		"}",
		".panel-settings .slider-bar {",
		"	background-color: #dedede;",
		"}",
		".panel-settings .slider-label {",
		"	color: #888;",
		"}",
		".nano>.nano-pane>.nano-slider {",
		"	background-color: #c2c2c2;",
		"}",
		".nano>.nano-pane>.nano-slider:hover {",
		"	background-color: #0096ff;",
		"}",
		".nano-card-link .icon {",
		"	color: #c2c2c2;",
		"}",
		".nano-card-link:hover .icon {",
		"	color: #444;",
		"	-webkit-text-stroke: #444 .5px;",
		"}",
		".panel-search-history .heading-bordered {",
		"	border-bottom: 1px solid #9b9b9b;",
		"}",
		".page-sidebar .profile .profile-settings {",
		"	color: #a2a2a2;",
		"	cursor: pointer;",
		"	margin-top: -18px;",
		"	padding: 10px;",
		"	position: absolute;",
		"	right: 4px;",
		"	top: 50%;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".page-sidebar .profile .profile-settings.active-panel, .page-sidebar .profile .profile-settings:focus, .page-sidebar .profile .profile-settings:hover {",
		"	color: #ff6400;",
		"}",
		".nano-card-item {",
		"	background-color: #f8f8f8;",
		"}",
		".nano-card-link {",
		"	/*background-color: #f9f9f9;*/",
		"	background-color: transparent;",
		"}",
		".nano-card-item.has-contextmenu, .nano-card-item:hover {",
		"	background-color: #efefef;",
		"}",
		".nano-card-options .option {",
		"	color: #777;",
		"	display: inline-block;",
		"	transition-duration: .15s;",
		"	transition-property: color;",
		"}",
		".nano-card-options .option:hover {",
		"	color: #ff6400;",
		"}",
		".page-sidebar .player-progress .progress-seek-overlay {",
		"	background-color: #fff;",
		"	opacity: .075;",
		"	/*border-right: 5px groove rgba(150,150,150,.4);*/",
		"	backdrop-filter: grayscale(100%) contrast(130%) brightness(70%);",
		"	-moz-backdrop-filter: grayscale(100%) contrast(130%) brightness(70%);",
		"	-webkit-backdrop-filter: grayscale(100%) contrast(130%) brightness(70%);",
		"}",
		".page-panels .panel-body:not(.lyrics-panel-body), .nano-card-item {",
		"	background-color: #f8f8f8;",
		"}",
		".panel-apps .app-suggest {",
		"	background-color: #f8f8f8;",
		"}",
		".panel-notifications .notifications-item {",
		"	background-color: #f8f8f8;",
		"	border-bottom: 1px solid #efefef;",
		"}",
		".panel-notifications .notifications-item:hover {",
		"	background-color: #efefef;",
		"}",
		"#page_feed .footer .time {",
		"	color: #ccc;",
		"}",
		".thumbnail .action-item-btn {",
		"	background-color: #000;",
		"	color: #fff;",
		"	transition-property: opacity,transform,-webkit-transform,background-color,color,box-shadow;",
		"}",
		".thumbnail .action-item-btn:hover {",
		"	background-color: #0096ff;",
		"	color: #fff;",
		"	box-shadow: 0 0 2px 2px #000;",
		"}",
		".dropdown .dropdown-menu>li>a:hover, .dropdown .dropdown-menu>li>button:hover {",
		"	background-color: #f8f8f8;",
		"	color: #323232;",
		"}",
		".catalog-header .header-info .heading-link {",
		"	color: #ccc;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4-sub.heading-inverse {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4.heading-inverse:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4-sub.heading-inverse .lyrics-artist-link {",
		"	color: #0096ff;",
		"	-webkit-text-stroke: #0096ff .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".page-panels .panel-wrapper .panel-lyrics .heading-4-sub.heading-inverse .lyrics-artist-link:hover {",
		"	color: #ff6400;",
		"	-webkit-text-stroke: #ff6400 .5px;",
		"	text-shadow: 0 0 2px #000;",
		"}",
		".is-favorite .svg-icon {",
		"	/* backdrop-filter: invert(10%); */",
		"	/* -webkit-text-stroke: #fff .6px; */",
		"	/* outline: inset #fff; */",
		"	filter: drop-shadow(0px 0px 5px #000);",
		"	-webkit-filter: drop-shadow(0px 0px 5px #000);",
		"	-moz-filter: drop-shadow(0px 0px 5px #000);",
		"}",
		".is-favorite {",
		"	color: #ff0000;",
		"}",
		".datagrid-action:hover .is-favorite .svg-icon {",
		"	color: #fff !important;",
		"}",
		".btn-favorite>.action-active .icon-love, .btn-favorite>.action-active .svg-icon-love {",
		"	color: #ff1e1e;",
		"}",
		".btn-app .icon, .btn-app .svg-icon, .btn-default .icon, .btn-default .svg-icon, .btn-group>.btn-label .icon, .btn-group>.btn-label .svg-icon, .btn-slide .icon, .btn-slide .svg-icon, .btn-telco .icon, .btn-telco .svg-icon {",
		"	color: #fff;",
		"}",
		".svg-icon.active, .svg-icon.is-active {",
		"	fill: #0096ff;",
		"}",
		".cell-love .svg-icon.active, .cell-love .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon.active, .cell-love .datagrid-action:hover .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline.is-active, .cell-love .datagrid-action:hover .svg-icon-love-outline.is-active {",
		"	color: #fff;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline.is-active .svg-path, .cell-love .datagrid-action:hover .svg-icon-love-outline.is-active .svg-path {",
		"	fill: #ff1e1e;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline, .cell-love .datagrid-action:hover .svg-icon-love-outline {",
		"	color: #ddd;",
		"}",
		".cell-love .datagrid-action:hover .svg-icon-love-outline .svg-path, .cell-love .datagrid-action:hover .svg-icon-love-outline .svg-path {",
		"	fill: #444;",
		"}",
		".datagrid-row.song.active .cell-love .svg-icon.active, .datagrid-row.song.active .cell-love .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"	color: #000;",
		"	filter: drop-shadow(0px 0px 2px #000);",
		"}",
		".datagrid-row.song.active .cell-love .datagrid-action:hover .svg-icon.active, .datagrid-row.song.active .cell-love .datagrid-action:hover .svg-icon.is-active {",
		"	fill: #ff1e1e;",
		"	color: #fff;",
		"	filter: drop-shadow(0px 0px 2px #000);",
		"}",
		".datagrid-row.song.active .cell-love .svg-icon.active .svg-path, .datagrid-row.song.active .cell-love .svg-icon.is-active .svg-path {",
		"	/*fill-rule: evenodd;*/",
		"	fill: #ff1e1e;",
		"}",
		".svg-icon-love-outline.is-active {",
		"	color: #ff1e1e;",
		"	fill: none;",
		"}",
		".svg-icon-love-outline.is-active .svg-path {",
		"	fill: none;",
		"	fill-rule: nonzero;",
		"}",
		".navbar-item.active .navbar-link {",
		"	border-color: #0096ff;",
		"	color: #ff6400;",
		"}",
		"#page_account .account-labs .lab-title {",
		"	color: #ccc;",
		"}",
		"#page_account .account-labs .lab-name {",
		"	color: #0096ff;",
		"}",
		"#page_account .heading-2 {",
		"	color: #eee;",
		"}",
		"/* TEST 4 DROPDOWN */",
		"#page_profile .dropdown .dropdown-menu>li>a:hover, #page_profile .dropdown .dropdown-menu>li>button:hover {",
		"	background-color: #222;",
		"	color: #cdcdcd;",
		"}",
		"#page_profile .dropdown .dropdown-menu, #page_profile .dropdown .dropdown-menu>li>a, #page_profile .dropdown .dropdown-menu>li>button {",
		"	background-color: transparent;",
		"}",
		"#page_profile .dropdown .dropdown-menu>li>a, #page_profile .dropdown .dropdown-menu>li>button {",
		"	color: #ccc;",
		"}",
		"#page_profile .dropdown .dropdown-menu {",
		"	border-top: 1px solid #636363;",
		"	border-left: 1px solid #636363;",
		"	border-right: 1px solid #636363;",
		"	border-bottom: 1px solid #636363;",
		"}",
		"/* Tracklist 1st line of the header (grid) */",
		".datagrid-header .datagrid-row:after {",
		"	background-color: #ff640099;",
		"	background-color: rgba(255, 100, 0, .6);",
		"	height: 1px;",
		"	left: 6px;",
		"	position: absolute;",
		"	right: 6px;",
		"}",
		".datagrid-header .datagrid-row:hover:after {",
		"	background-color: #333;",
		"}",
		".datagrid-row:after {",
		"	background-color: #333;",
		"}",
		".page-notifications>.notification {",
		"	background-color: #0096ff;",
		"}",
		".page-notifications>.notification>h2 {",
		"	color: #fff;",
		"	text-align: center;",
		"}",
		"#page_profile {",
		"	background-color: #0a0a0a;",
		"}",
		"#page_profile .dropdown .dropdown-menu, #page_profile .dropdown .dropdown-menu>li>a, #page_profile .dropdown .dropdown-menu>li>button {",
		"	background-color: #0a0a0a;",
		"}",
		".datagrid-divider .datagrid-row {",
		"	background-color: #0a0a0a;",
		"	color: #ff6400;",
		"}",
		".datagrid-divider .datagrid-row:hover {",
		"	background-color: #333;",
		"}"
	].join("\n");
if (false || (document.domain == "deezer.com" || document.domain.substring(document.domain.indexOf(".deezer.com") + 1) == "deezer.com"))
	css += [
		"#dzdltrigger, #dzdownloader, #dzdownloader select {",
		"	filter: invert(1) hue-rotate(180deg) !important;",
		"}",
		"#dzdownloader select {",
		"	color: white;",
		"	background-color: black;",
		"}",
		"#dzdownloader {",
		"	color: #111;",
		"	background: #eee;",
		"}",
		"#dzdltrigger {",
		"	color: #11111155;",
		"	background: transparent;",
		"	font-weight: bold;",
		"	font-size: 8px;",
		"}",
		"#dzdltrigger:hover {",
		"	color: #111111;",
		"	cursor: pointer;",
		"}"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();